/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NetbooksRouteImport } from './routes/netbooks'
import { Route as ChamadosRouteImport } from './routes/chamados'
import { Route as IndexRouteImport } from './routes/index'

const NetbooksRoute = NetbooksRouteImport.update({
  id: '/netbooks',
  path: '/netbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadosRoute = ChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chamados': typeof ChamadosRoute
  '/netbooks': typeof NetbooksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chamados': typeof ChamadosRoute
  '/netbooks': typeof NetbooksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chamados': typeof ChamadosRoute
  '/netbooks': typeof NetbooksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chamados' | '/netbooks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chamados' | '/netbooks'
  id: '__root__' | '/' | '/chamados' | '/netbooks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChamadosRoute: typeof ChamadosRoute
  NetbooksRoute: typeof NetbooksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/netbooks': {
      id: '/netbooks'
      path: '/netbooks'
      fullPath: '/netbooks'
      preLoaderRoute: typeof NetbooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamados': {
      id: '/chamados'
      path: '/chamados'
      fullPath: '/chamados'
      preLoaderRoute: typeof ChamadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChamadosRoute: ChamadosRoute,
  NetbooksRoute: NetbooksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
